# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set([('owner', 'rent', 'object'), ('owner', 'vacancy', 'object')]),
        ),
    ]
