# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170220_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.RentRubric')),
            ],
            options={
                'verbose_name': '\u0420\u0443\u0431\u0440\u0438\u043a\u0430 \u0430\u0440\u0435\u043d\u0434\u044b',
                'verbose_name_plural': '\u0420\u0443\u0431\u0440\u0438\u043a\u0438 \u0430\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='rentRubrics',
            field=models.ManyToManyField(blank=True, null=True, to='core.RentRubric'),
        ),
    ]
