# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170325_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
