# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
