# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20170201_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0410\u0440\u0435\u043d\u0434\u0430',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u0430\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set([('owner', 'vacancy', 'object')]),
        ),
    ]
