# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20170209_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rent'),
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set([('owner', 'vacancy', 'rent', 'object')]),
        ),
    ]
