# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170210_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent'),
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set([('owner', 'rent', 'object'), ('owner', 'vacancy', 'object')]),
        ),
    ]
