# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170212_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='rubrics',
            field=models.ManyToManyField(blank=True, null=True, to='core.Rubric'),
        ),
    ]
