# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170212_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rent'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vacancy'),
        ),
    ]
