# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170217_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.CharField(default='1000 \u0440.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.CharField(default='2000 \u0440.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set([]),
        ),
    ]
