# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170218_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
