# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170220_1143'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='rubrics',
            field=models.ManyToManyField(to='core.Rubric'),
        ),
    ]
