# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170113_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
