# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_resume_rubrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
