# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='ad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extuser',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extuser',
            name='edu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extuser',
            name='filmography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='extuser',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='extuser',
            name='rubrics',
            field=models.ManyToManyField(to='core.Rubric'),
        ),
        migrations.AddField(
            model_name='extuser',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
