# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_resume_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='rubrics',
            field=models.ManyToManyField(blank=True, null=True, to='core.Rubric'),
        ),
    ]
