# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_is_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_saved',
            new_name='isSaved',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_worker',
            new_name='isWorker',
        ),
    ]
