# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170127_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rubrics',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='rubrics',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
