# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170116_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Text',
            field=models.TextField(blank=True),
        ),
    ]
