# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170203_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('edu', models.TextField(blank=True, null=True)),
                ('filmography', models.TextField(blank=True, null=True)),
                ('ad', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0437\u044e\u043c\u0435',
                'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u0440\u0435\u0437\u044e\u043c\u0435',
            },
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='filmography',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='text',
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
