# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170324_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='phoneIsActive',
            field=models.BooleanField(default=False),
        ),
    ]
