# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Text',
            new_name='text',
        ),
    ]
