# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170206_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='owner',
        ),
    ]
